name: Feature Request
description: Suggest a new feature or enhancement
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your suggestion. Please describe the feature you'd like.
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What are you trying to do?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How do you think this should work?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative approaches you've thought about.
  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - Spatial backends (murk-space)
        - Propagator pipeline (murk-propagator)
        - Observation system (murk-obs)
        - Engine (murk-engine)
        - Python bindings (murk-python)
        - C FFI (murk-ffi)
        - Replay system (murk-replay)
        - Documentation
        - Other
    validations:
      required: true
